zuul:
  routes:
    service-a:
      path: /list/**
      serviceId: main-service
    service-b:
      path: /book/**
      serviceId: booking-service

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST}"